
export const EXPERTISE_SUGGESTIONS = [
  'Software Engineering',
  'Product Management',
  'UI/UX Design',
  'Data Science',
  'Artificial Intelligence',
  'Marketing',
  'Sales',
  'Finance',
  'Venture Capital',
  'Healthcare',
  'Biotechnology',
  'Education Technology',
  'E-commerce',
  'Retail',
  'Sustainability',
  'Green Tech',
  'Urban Planning',
  'Logistics',
  'Transportation',
  'Hardware Engineering',
  'Cybersecurity',
  'Fintech',
  'Legal',
  'Human Resources',
];
